# Generated by Django 4.1.7 on 2024-06-22 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('objetivos', models.CharField(max_length=400)),
                ('actividades', models.CharField(max_length=400)),
                ('recursos', models.CharField(max_length=400)),
                ('cierreTutorias', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='BajaAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.FileField(upload_to='evidenciaAccionTutorial/')),
                ('accionRutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.acciontutorial')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('respuestaUno', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asuntoTratar', models.CharField(max_length=400)),
                ('observaciones', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField()),
                ('bajasAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.bajaalumnos')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='acciontutorial',
            name='cicloAccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.periodo'),
        ),
        migrations.AddField(
            model_name='acciontutorial',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.usuarios'),
        ),
    ]
