# Generated by Django 5.0.6 on 2024-06-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_acciontutorial_bajaalumnos_periodo_evidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajaalumnos',
            name='motivo',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bajaalumnos',
            name='observaciones',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bajaalumnos',
            name='tipo',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acciontutorial',
            name='cierreTutorias',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Canalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
                ('detalles', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('FechaInicio', models.DateTimeField()),
                ('FechaFinal', models.DateTimeField()),
                ('atencionIndividual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.atencionindividual')),
            ],
        ),
    ]
